<font color=#1E8449>☘ </font> 注意事項
1. 如果您使用 Colab，在您熟悉 Colab 的操作環境之後，建議把介面改成英文版，以便讓程式碼有最好的顯示效果
 * 選擇 Colab 功能表裡的 <font color=#E59866>說明</font> - <font color=#E59866>查看英文版本</font> 即可將介面改成英文版
 * 要改回中文版，請關掉目前開啟的 Colab 網頁，再重新開啟您執行的 Colab 檔案即可（Colab 預設為中文版）
2. 建議選擇暗色背景，長時間撰寫程式時眼睛會比較舒服
 * 在 Colab 裡選擇 <font color=#E59866>Tools（工具）</font> - <font color=#E59866> Settings （設定）</font> - <font color=#E59866> Site（網站）</font> - <font color=#E59866> Theme （主題）</font> - <font color=#E59866> Dark </font>
 * 在 Jupyter lab 中選擇 <font color=#E59866> Settings </font> - <font color=#E59866> JupyterLab theme </font> - <font color=#E59866> JupyerterLab Dark </font>



## Chap 09 使用 Numpy 套件

### 9.1 認識 Numpy 的陣列

In [ ]:
import numpy as np

#### 9.1.1 Numpy 陣列的基本認識

In [ ]:
np.array([3,2,5])

array([3, 2, 5])

In [ ]:
a=np.array((0,1,2,3,4)) 

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
a.ndim

1

In [ ]:
a.shape

(5,)

In [ ]:
a.size

5

In [ ]:
len(a)

5

In [ ]:
a.dtype    

dtype('int64')

In [ ]:
b=np.array([[1,3,2],
            [4,7,9]])

In [ ]:
b

array([[1, 3, 2],
       [4, 7, 9]])

In [ ]:
b.ndim

2

In [ ]:
b.shape

(2, 3)

In [ ]:
b.size

6

In [ ]:
a=np.array([[1,2,3,4]])   # row vector

In [ ]:
a

array([[1, 2, 3, 4]])

In [ ]:
a.ndim

2

In [ ]:
a.shape

(1, 4)

In [ ]:
b=np.array([[1],[2],[3],[4]])  # column vector

In [ ]:
b

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
b.ndim

2

In [ ]:
b.shape

(4, 1)

In [ ]:
c=np.array([[12]])

In [ ]:
c.ndim

2

In [ ]:
c.shape

(1, 1)

In [ ]:
np.array([12]).shape

(1,)

In [ ]:
np.array(12).shape

()

In [ ]:
np.array(12).ndim

0

In [ ]:
a=np.array([[0,1,3,3],[4,7,9,8],[5,4,8,2]])

In [ ]:
a

array([[0, 1, 3, 3],
       [4, 7, 9, 8],
       [5, 4, 8, 2]])

In [ ]:
lst=[[[1,2,3,0],
      [3,4,5,0],
      [5,6,7,1]],
     [[7,8,9,1],
      [8,2,2,1],
      [1,2,4,6]]]

In [ ]:
a=np.array(lst)

In [ ]:
a

array([[[1, 2, 3, 0],
        [3, 4, 5, 0],
        [5, 6, 7, 1]],

       [[7, 8, 9, 1],
        [8, 2, 2, 1],
        [1, 2, 4, 6]]])

In [ ]:
a.ndim

3

In [ ]:
a.shape

(2, 3, 4)

In [ ]:
a.size

24

#### 9.1.2 Numpy 提供的資料型別

In [ ]:
a=np.array([1,2,3])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
np.array([1.,2.,3.]).dtype

dtype('float64')

In [ ]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [ ]:
np.array([True,False,True]).dtype

dtype('bool')

In [ ]:
np.array([0,1,4,0],dtype=bool)

array([False,  True,  True, False])

In [ ]:
np.array([-3,72,300],dtype='uint8')

array([253,  72,  44], dtype=uint8)

In [ ]:
a=np.array([[1.2,4.0],[6.9,8.3]])

In [ ]:
a.dtype

dtype('float64')

In [ ]:
a.astype(int)    

array([[1, 4],
       [6, 8]])

In [ ]:
a.dtype

dtype('float64')

In [ ]:
a.tolist()      

[[1.2, 4.0], [6.9, 8.3]]

In [ ]:
a

array([[1.2, 4. ],
       [6.9, 8.3]])

In [ ]:
np.array(['Tom','Jerry'])   

array(['Tom', 'Jerry'], dtype='<U5')

In [ ]:
np.array(['青花瓷','素胚勾勒出青花'])

array(['青花瓷', '素胚勾勒出青花'], dtype='<U7')

In [ ]:
np.array(['',[3,8]],dtype=object)   

array(['', list([3, 8])], dtype=object)

In [ ]:
n_str=np.array(['4.3','-4.3','9'])

In [ ]:
n_str.dtype

dtype('<U4')

In [ ]:
n_str.astype(float)

array([ 4.3, -4.3,  9. ])

#### 9.1.3 用來建立陣列的函數

In [ ]:
np.arange(10)   

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(0,1,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [ ]:
np.arange(0,1.001,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
np.linspace(0,1,5,endpoint=False)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((1,5),dtype='int32')

array([[1, 1, 1, 1, 1]], dtype=int32)

In [ ]:
np.empty((4,2))

array([[4.63799403e-310, 2.46151512e-312],
       [9.76118064e-313, 2.46151512e-312],
       [2.37663529e-312, 4.99006302e-322],
       [0.00000000e+000, 0.00000000e+000]])

In [ ]:
np.diag([3,4,5])

array([[3, 0, 0],
       [0, 4, 0],
       [0, 0, 5]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.tile(np.array([[1,2],[3,4]]),(2,3))

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [ ]:
np.tile([['r','g'],['g','b']],(2,2))

array([['r', 'g', 'r', 'g'],
       ['g', 'b', 'g', 'b'],
       ['r', 'g', 'r', 'g'],
       ['g', 'b', 'g', 'b']], dtype='<U1')

#### 9.1.4 亂數的產生

In [ ]:
np.random.seed(999)

In [ ]:
np.random.randint(1,7,6)

array([1, 5, 6, 2, 1, 2])

In [ ]:
np.random.randint(1,7,(2,3))

array([[4, 2, 4],
       [1, 6, 6]])

In [ ]:
np.random.rand(3,2)

array([[0.75606364, 0.17987637],
       [0.74347915, 0.49299622],
       [0.47596572, 0.51063269]])

In [ ]:
np.random.randn(4,2)

array([[-0.29663457, -0.92292269],
       [ 0.13599166, -0.16389124],
       [ 0.42700972,  0.25089136],
       [-0.57042602,  2.29817186]])

In [ ]:
rg = np.random.default_rng(seed=998)

In [ ]:
rg.random((3,2))

array([[0.69978223, 0.31861007],
       [0.56187721, 0.25601819],
       [0.85290293, 0.88627787]])

In [ ]:
rg.integers(3,5,(2,6))

array([[4, 4, 3, 4, 3, 4],
       [4, 4, 4, 3, 3, 3]])

In [ ]:
rg.standard_normal((3,2))

array([[ 1.16245766,  1.32657771],
       [-0.7115124 , -0.47858946],
       [-0.23327976,  1.00268381]])

In [ ]:
a=[1,2,3,4,5]

In [ ]:
rg.permutation(a)

array([3, 2, 4, 1, 5])

In [ ]:
a

[1, 2, 3, 4, 5]

In [ ]:
rg.shuffle(a)   

In [ ]:
a

[2, 5, 3, 1, 4]

In [ ]:
rg.choice(range(5),4)    

array([1, 3, 4, 1])

In [ ]:
rg.choice(range(5),4,replace=False)

array([2, 3, 4, 0])

In [ ]:
a=np.arange(15).reshape(3,5)

In [ ]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
rg.choice(a,4,axis=1)

array([[ 3,  4,  2,  4],
       [ 8,  9,  7,  9],
       [13, 14, 12, 14]])

In [ ]:
rg.choice(a,2,axis=0,replace=False)

array([[10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

In [ ]:
rg.permutation(a,axis=1)

array([[ 1,  2,  4,  3,  0],
       [ 6,  7,  9,  8,  5],
       [11, 12, 14, 13, 10]])

### 9.2 陣列元素的提取

#### 9.2.1 索引值的操作

In [ ]:
a=np.array([3,8,9,7])

In [ ]:
a[0],a[1],a[-1],a[-2]

(3, 8, 7, 9)

In [ ]:
b=np.array([[3,4,5,7],
            [6,8,1,0],
            [8,9,3,4]])

In [ ]:
b[0]

array([3, 4, 5, 7])

In [ ]:
b[0,2]

5

In [ ]:
b[(0,2)]

5

In [ ]:
b[0][2]

5

In [ ]:
b.shape

(3, 4)

In [ ]:
b[-1]

array([8, 9, 3, 4])

In [ ]:
b[-1]=[1,2,9,9]

In [ ]:
b

array([[3, 4, 5, 7],
       [6, 8, 1, 0],
       [1, 2, 9, 9]])

In [ ]:
b[0]=0

In [ ]:
b

array([[0, 0, 0, 0],
       [6, 8, 1, 0],
       [1, 2, 9, 9]])

In [ ]:
b.dtype

dtype('int64')

In [ ]:
b[0,2]=12.7   

In [ ]:
b

array([[ 0,  0, 12,  0],
       [ 6,  8,  1,  0],
       [ 1,  2,  9,  9]])

In [ ]:
b.dtype

dtype('int64')

In [ ]:
np.random.seed(999)

In [ ]:
c=np.random.randint(0,256,(3,2,4))   

In [ ]:
c

array([[[192,  92, 101, 225],
        [200, 225, 219, 159]],

       [[217, 179,  16, 237],
        [117,   8, 136, 176]],

       [[ 69,  66,  11,  11],
        [149, 215, 228, 250]]])

In [ ]:
c[0]

array([[192,  92, 101, 225],
       [200, 225, 219, 159]])

In [ ]:
c[0,1]

array([200, 225, 219, 159])

In [ ]:
c[0][1]

array([200, 225, 219, 159])

In [ ]:
c[0,0,2]

101

#### 9.2.2 陣列的切片操作

<font color=#1EA004>☘ </font>  For one dimensional array

In [ ]:
a=np.arange(10)

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[2:10:3]

array([2, 5, 8])

In [ ]:
a[2:10]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[:4]    

array([0, 1, 2, 3])

In [ ]:
a[5:]

array([5, 6, 7, 8, 9])

In [ ]:
a[3::2]   

array([3, 5, 7, 9])

In [ ]:
a[::3]   

array([0, 3, 6, 9])

In [ ]:
a[::-1]   

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
a[2::-1]   

array([2, 1, 0])

In [ ]:
a[-3:1:-2]

array([7, 5, 3])

In [ ]:
a[3::2]

array([3, 5, 7, 9])

In [ ]:
a[2:5]=0.3

In [ ]:
a

array([0, 1, 0, 0, 0, 5, 6, 7, 8, 9])

In [ ]:
a=np.arange(30).reshape(5,6)

In [ ]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
a[0,2:]

array([2, 3, 4, 5])

In [ ]:
a[0,::-1]

array([5, 4, 3, 2, 1, 0])

In [ ]:
a[2:,:]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
a[::-1,::-1]

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [ ]:
a[3,:]

array([18, 19, 20, 21, 22, 23])

In [ ]:
a[:,2]

array([ 2,  8, 14, 20, 26])

In [ ]:
a[:,2:3]   

array([[ 2],
       [ 8],
       [14],
       [20],
       [26]])

In [ ]:
a[::2,::2] 

array([[ 0,  2,  4],
       [12, 14, 16],
       [24, 26, 28]])

In [ ]:
a[2:4]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

#### 9.2.3 利用布林值提取元素

In [ ]:
a=np.array([22,65,36,45,79,12,17])

In [ ]:
[i for i in a if i%2==0]

[22, 36, 12]

In [ ]:
even=(a%2==0)

In [ ]:
even

array([ True, False,  True, False, False,  True, False])

In [ ]:
a[even]

array([22, 36, 12])

In [ ]:
a[even]=0

In [ ]:
a

array([ 0, 65,  0, 45, 79,  0, 17])

In [ ]:
b=np.array([[1,2,3],[2,6,4],[8,3,2]])

In [ ]:
b>3

array([[False, False, False],
       [False,  True,  True],
       [ True, False, False]])

In [ ]:
b[b>3]

array([6, 4, 8])

In [ ]:
b[b==2].size

3

In [ ]:
b[b%2==0]

array([2, 2, 6, 4, 8, 2])

In [ ]:
b[:,[True,False,True]]

array([[1, 3],
       [2, 4],
       [8, 2]])

#### 9.2.4 利用整數陣列提取元素

In [ ]:
a=np.array([9,17,23,34,45,56,67,78])

In [ ]:
a[:3]   

array([ 9, 17, 23])

In [ ]:
a[np.arange(len(a))<3]  

array([ 9, 17, 23])

In [ ]:
a[[0,1,2]]   

array([ 9, 17, 23])

In [ ]:
a[[0,2,2,1]] 

array([ 9, 23, 23, 17])

In [ ]:
a[np.array([0,2,2,1])]   

array([ 9, 23, 23, 17])

In [ ]:
idx=np.array([[2,2,3],
              [1,5,6]])  

In [ ]:
a[idx] 

array([[23, 23, 34],
       [17, 56, 67]])

In [ ]:
a[[3,-2,-1]]=-1 

In [ ]:
a

array([ 9, 17, 23, -1, 45, 56, -1, -1])

In [ ]:
a=np.arange(0,20).reshape(4,5)

In [ ]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
a[[0,1,3],[3,1,4]]

array([ 3,  6, 19])

In [ ]:
a[1:4,4]

array([ 9, 14, 19])

In [ ]:
a[1:4,[4,3]]

array([[ 9,  8],
       [14, 13],
       [19, 18]])

In [ ]:
a[[0,1,3],2:4]

array([[ 2,  3],
       [ 7,  8],
       [17, 18]])

In [ ]:
a[2:4,[1,2,4]]

array([[11, 12, 14],
       [16, 17, 19]])

In [ ]:
a[[3,1,0],[4,3,1]]   

array([19,  8,  1])

In [ ]:
a[[3,1],::2] 

array([[15, 17, 19],
       [ 5,  7,  9]])

In [ ]:
a[[0,1,3],:][:,[1,3]]   

array([[ 1,  3],
       [ 6,  8],
       [16, 18]])

In [ ]:
mask=np.array([1,0,1,1,0],dtype=bool)

In [ ]:
mask

array([ True, False,  True,  True, False])

In [ ]:
a[0,mask]

array([0, 2, 3])

In [ ]:
a[-1,mask]

array([15, 17, 18])

In [ ]:
a[1:,mask]

array([[ 5,  7,  8],
       [10, 12, 13],
       [15, 17, 18]])

In [ ]:
a[:,mask][[1,3],:]

array([[ 5,  7,  8],
       [15, 17, 18]])

In [ ]:
a[[1,3]][:,[0,2]]

array([[ 5,  7],
       [15, 17]])

#### 9.2.5 拷貝與檢視

In [ ]:
a1=np.array([0,1,2,3,4,6,7,8])

In [ ]:
b=a1[2:5]  # b is a view of a

In [ ]:
b

array([2, 3, 4])

In [ ]:
b[0:2]=99

In [ ]:
b

array([99, 99,  4])

In [ ]:
a1

array([ 0,  1, 99, 99,  4,  6,  7,  8])

In [ ]:
a2=np.array([0,1,2,3,4,5,6,7,8])

In [ ]:
c=a2[[0,3,7]]

In [ ]:
c

array([0, 3, 7])

In [ ]:
c[0:2]=99

In [ ]:
c

array([99, 99,  7])

In [ ]:
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.shares_memory(a1,b)

True

In [ ]:
np.shares_memory(a2,c)

False

In [ ]:
d=a2[3:].copy()

In [ ]:
np.shares_memory(a2,d)

False

In [ ]:
e=a2[a2<5]

In [ ]:
e

array([0, 1, 2, 3, 4])

In [ ]:
np.shares_memory(a2,e)

False

### 9.3 改變陣列的大小與維度

#### 9.3.1 攤平與重排

In [ ]:
a=np.array([1,2,3,4,5,6])

In [ ]:
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
b=a.reshape(2,3)  

In [ ]:
np.shares_memory(a,b)    

True

In [ ]:
b   

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a  

array([1, 2, 3, 4, 5, 6])

In [ ]:
b.ravel()

array([1, 2, 3, 4, 5, 6])

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b.flatten()

array([1, 2, 3, 4, 5, 6])

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
b.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [ ]:
b[1,2]=100

In [ ]:
a  

array([  1,   2,   3,   4,   5, 100])

In [ ]:
a=np.arange(6).reshape(2,3)

In [ ]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
b=a.flatten()  

In [ ]:
b

array([0, 1, 2, 3, 4, 5])

In [ ]:
np.shares_memory(a,b)

False

In [ ]:
b[0]=99    

In [ ]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
c=a.ravel()   

In [ ]:
np.shares_memory(a,c)

True

In [ ]:
c[0]=99

In [ ]:
a

array([[99,  1,  2],
       [ 3,  4,  5]])

#### 9.3.2 增加與調整維度

In [ ]:
a=np.array([1,2,3])

In [ ]:
b=a[np.newaxis,:]

In [ ]:
b

array([[1, 2, 3]])

In [ ]:
a

array([1, 2, 3])

In [ ]:
np.shares_memory(a,b)

True

In [ ]:
a[:,np.newaxis]  

array([[1],
       [2],
       [3]])

In [ ]:
a=np.arange(6).reshape(2,-1)

In [ ]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a[np.newaxis,:,:]     

array([[[0, 1, 2],
        [3, 4, 5]]])

In [ ]:
a[:,np.newaxis,:]   

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [ ]:
a[:,:,np.newaxis]   

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [ ]:
b=a.reshape(1,2,3)

In [ ]:
b

array([[[0, 1, 2],
        [3, 4, 5]]])

In [ ]:
b.squeeze()

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a=np.array([[1,2,3],
            [4,5,6]])

In [ ]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
b=a.transpose()

In [ ]:
a[0,2]==b[2,0]

True

In [ ]:
a=np.arange(24).reshape(2,4,3)

In [ ]:
a   

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [ ]:
a.T   

array([[[ 0, 12],
        [ 3, 15],
        [ 6, 18],
        [ 9, 21]],

       [[ 1, 13],
        [ 4, 16],
        [ 7, 19],
        [10, 22]],

       [[ 2, 14],
        [ 5, 17],
        [ 8, 20],
        [11, 23]]])

In [ ]:
a.T.shape

(3, 4, 2)

In [ ]:
b=a.transpose(2,1,0)  

In [ ]:
a[0,1,2]==b[2,1,0]

True

In [ ]:
a.swapaxes(2,1)

array([[[ 0,  3,  6,  9],
        [ 1,  4,  7, 10],
        [ 2,  5,  8, 11]],

       [[12, 15, 18, 21],
        [13, 16, 19, 22],
        [14, 17, 20, 23]]])

In [ ]:
np.moveaxis(a,0,2)    

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14]],

       [[ 3, 15],
        [ 4, 16],
        [ 5, 17]],

       [[ 6, 18],
        [ 7, 19],
        [ 8, 20]],

       [[ 9, 21],
        [10, 22],
        [11, 23]]])

In [ ]:
#np.transpose(a,(1,2,0))

#### 9.3.3 陣列的分隔與合併

In [ ]:
a=np.array([[1,2,3,4,5,3],
            [5,6,7,8,2,0]])

In [ ]:
np.split(a,2,axis=1)      

[array([[1, 2, 3],
        [5, 6, 7]]), array([[4, 5, 3],
        [8, 2, 0]])]

In [ ]:
np.split(a,[2],axis=1)    

[array([[1, 2],
        [5, 6]]), array([[3, 4, 5, 3],
        [7, 8, 2, 0]])]

In [ ]:
np.split(a,[2,3],axis=1)   

[array([[1, 2],
        [5, 6]]), array([[3],
        [7]]), array([[4, 5, 3],
        [8, 2, 0]])]

In [ ]:
np.vsplit(a,2)   

[array([[1, 2, 3, 4, 5, 3]]), array([[5, 6, 7, 8, 2, 0]])]

In [ ]:
a=np.arange(16).reshape(4,4); a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
a1,a2=np.vsplit(a,2) 

In [ ]:
a1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
a2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.vstack((a1,a2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hstack((a1,a2))

array([[ 0,  1,  2,  3,  8,  9, 10, 11],
       [ 4,  5,  6,  7, 12, 13, 14, 15]])

In [ ]:
np.stack((a1,a2),axis=0)   

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
np.stack((a1,a2),axis=0).shape

(2, 2, 4)

In [ ]:
a=np.arange(24).reshape(4,6)

In [ ]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
vs=np.vsplit(a,2)

In [ ]:
vs

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [ ]:
b=np.array([np.hsplit(v,3) for v in vs])


In [ ]:
b.shape   

(2, 3, 2, 2)

In [ ]:
b[0,0]

array([[0, 1],
       [6, 7]])

In [ ]:
b[1,2]

array([[16, 17],
       [22, 23]])

In [ ]:
np.vstack([np.hstack(i) for i in b])

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])