<font color=#1E8449>☘ </font> 注意事項
1. 如果您使用 Colab，在您熟悉 Colab 的操作環境之後，建議把介面改成英文版，以便讓程式碼有最好的顯示效果
 * 選擇 Colab 功能表裡的 <font color=#E59866>說明</font> - <font color=#E59866>查看英文版本</font> 即可將介面改成英文版
 * 要改回中文版，請關掉目前開啟的 Colab 網頁，再重新開啟您執行的 Colab 檔案即可（Colab 預設為中文版）
2. 建議選擇暗色背景，長時間撰寫程式時眼睛會比較舒服
 * 在 Colab 裡選擇 <font color=#E59866>Tools（工具）</font> - <font color=#E59866> Settings （設定）</font> - <font color=#E59866> Site（網站）</font> - <font color=#E59866> Theme （主題）</font> - <font color=#E59866> Dark </font>
 * 在 Jupyter lab 中選擇 <font color=#E59866> Settings </font> - <font color=#E59866> JupyterLab theme </font> - <font color=#E59866> JupyerterLab Dark </font>



## Chap 10 Numpy 的數學運算

In [ ]:
import numpy as np

### 10.1 基本計算

#### 10.1.1 常數與數學函數

In [ ]:
np.pi

3.141592653589793

In [ ]:
np.inf+100

inf

In [ ]:
np.inf/np.inf

nan

In [ ]:
np.nan*34

nan

In [ ]:
np.e

2.718281828459045

In [ ]:
a=np.array([0,1,2])

In [ ]:
b=[0,1,2]

In [ ]:
[i+3 for i in b]

[3, 4, 5]

In [ ]:
a+3

array([3, 4, 5])

In [ ]:
a**2

array([0, 1, 4])

In [ ]:
a*a

array([0, 1, 4])

In [ ]:
a**[2,2,3]  # 次方

array([0, 1, 8])

In [ ]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356])

In [ ]:
np.sin(a)

array([0.        , 0.84147098, 0.90929743])

In [ ]:
np.set_printoptions(3)    

In [ ]:
np.sin(a)

array([0.   , 0.841, 0.909])

In [ ]:
np.sin([0,2,4])

array([ 0.   ,  0.909, -0.757])

In [ ]:
np.degrees(np.pi/2)

90.0

In [ ]:
np.radians([0,90,180])

array([0.   , 1.571, 3.142])

In [ ]:
np.set_printoptions(8)

In [ ]:
np.mod([78,80,93],2)

array([0, 0, 1])

In [ ]:
np.mod([12,9,8],[2,2,3])

array([0, 1, 2])

In [ ]:
np.round(12.37,1)

12.4

In [ ]:
np.log2(1024)

10.0

In [ ]:
np.log(np.exp([1,2,4]))

array([1., 2., 4.])

In [ ]:
np.modf([6.12,3.9,6,12.4])

(array([0.12, 0.9 , 0.  , 0.4 ]), array([ 6.,  3.,  6., 12.]))

In [ ]:
np.maximum([4,5,4],[1,2,7])

array([4, 5, 7])

In [ ]:
np.minimum([4,5,4],[1,2,7])

array([1, 2, 4])

In [ ]:
np.ceil([0.1, 4.7, 3.01])

array([1., 5., 4.])

In [ ]:
np.floor([5.38,4.99, 3.01])

array([5., 4., 3.])

In [ ]:
a=np.array([0,2,3,4])

In [ ]:
b=np.array([0,3,0,4])

In [ ]:
a>b

array([False, False,  True, False])

In [ ]:
a[a<=b]

array([0, 2, 4])

In [ ]:
np.array_equal(a,b)

False

In [ ]:
np.logical_and(a,b)

array([False,  True, False,  True])

In [ ]:
np.logical_or(a,b)

array([False,  True,  True,  True])

In [ ]:
np.logical_xor(a,b)

array([False, False,  True, False])

In [ ]:
np.logical_not(a)

array([ True, False, False, False])

#### 10.1.2 常用的陣列處理函數

In [ ]:
a=np.array([0,1,2,3,4,5])

In [ ]:
a.sum()

15

In [ ]:
np.sum(a)

15

In [ ]:
a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

In [ ]:
a.sum()

45

In [ ]:
a.sum(axis=0)   

array([12, 15, 18])

In [ ]:
a.sum(axis=1)   

array([ 6, 15, 24])

In [ ]:
a[:,-1].sum()

18

In [ ]:
np.random.seed(999)

In [ ]:
b=np.random.randint(0,2,(2,3,4))

In [ ]:
b

array([[[0, 0, 1, 1],
        [0, 1, 1, 1],
        [1, 1, 0, 1]],

       [[1, 0, 0, 0],
        [1, 0, 1, 1],
        [1, 1, 0, 0]]])

In [ ]:
b[0].sum()

8

In [ ]:
b[1].sum(axis=0)

array([3, 1, 1, 1])

In [ ]:
b[1].sum(axis=0)[[0,-1]]

array([3, 1])

In [ ]:
c=np.array([[4,3,8,1],
            [3,9,0,2],
            [6,9,7,5]])

In [ ]:
np.min(c)

0

In [ ]:
np.max(c)

9

In [ ]:
np.max(c,axis=1)

array([8, 9, 9])

In [ ]:
c.argmin()

6

In [ ]:
np.unravel_index(6, c.shape)

(1, 2)

In [ ]:
c.argmax()

5

In [ ]:
np.unravel_index(5, c.shape)

(1, 1)

In [ ]:
c.argmax(axis=0)

array([2, 1, 0, 2])

In [ ]:
c.argmax(axis=1)

array([2, 1, 1])

In [ ]:
np.where([True,False,True])

(array([0, 2]),)

In [ ]:
row,col=np.where(c==c.max())   

In [ ]:
row

array([1, 2])

In [ ]:
col

array([1, 1])

In [ ]:
c[row,col]   

array([9, 9])

In [ ]:
np.unravel_index([4,1,2],(2,3))

(array([1, 0, 0]), array([1, 1, 2]))

In [ ]:
np.ravel_multi_index([[1, 0, 0],[1, 1, 2]],(2,3))

array([4, 1, 2])

In [ ]:
d=np.array([7,3,5])

In [ ]:
np.where(d>4,10,20)

array([10, 20, 10])

In [ ]:
np.where(d>4,[10,11,12],[20,21,22])

array([10, 21, 12])

In [ ]:
np.all(np.array([1,4,0]))

False

In [ ]:
np.any(np.array([1,4,0]))

True

In [ ]:
np.any(np.array([1,3,-2,7,8])<0)

True

In [ ]:
np.array([[0,1],
          [3,4]]).all(axis=0)

array([False,  True])

In [ ]:
np.array([[0,1],
          [3,4]]).any(axis=1)

array([ True,  True])

In [ ]:
a=np.array([[3,4,5,4],
            [6,0,8,0],
            [6,0,8,0]])

In [ ]:
np.unique(a,axis=1)

array([[3, 4, 5],
       [6, 0, 8],
       [6, 0, 8]])

In [ ]:
np.unique(a,axis=0)

array([[3, 4, 5, 4],
       [6, 0, 8, 0]])

In [ ]:
np.unique(a)

array([0, 3, 4, 5, 6, 8])

In [ ]:
a.mean()

3.6666666666666665

In [ ]:
a.mean(axis=1)

array([4. , 3.5, 3.5])

In [ ]:
np.median(a)   

4.0

In [ ]:
a.std()

2.953340857778225

In [ ]:
a.var(axis=0)

array([2.        , 3.55555556, 2.        , 3.55555556])

In [ ]:
np.percentile(a,50)

4.0

In [ ]:
np.percentile(a,25,axis=0)

array([4.5, 0. , 6.5, 0. ])

### 10.2 資料的排序

In [ ]:
a=np.array([17,88,12,93,32,67])

In [ ]:
b=np.sort(a)

In [ ]:
b

array([12, 17, 32, 67, 88, 93])

In [ ]:
np.shares_memory(a,b)

False

In [ ]:
c=a.sort()   # sort a in-place

In [ ]:
print(c)

None


In [ ]:
a

array([12, 17, 32, 67, 88, 93])

In [ ]:
a[::-1]

array([93, 88, 67, 32, 17, 12])

In [ ]:
a=np.array([71,77,25,19])

In [ ]:
idx=np.argsort(a)

In [ ]:
idx

array([3, 2, 0, 1])

In [ ]:
b=np.sort(a)

In [ ]:
b

array([19, 25, 71, 77])

In [ ]:
c=np.zeros(np.shape(a),dtype=int)

In [ ]:
c[idx]=b   

In [ ]:
c

array([71, 77, 25, 19])

In [ ]:
a=np.array([[78,87,43],
            [98,12,47]])

In [ ]:
np.sort(a)   # default axis=-1

array([[43, 78, 87],
       [12, 47, 98]])

In [ ]:
np.sort(a,axis=0) 

array([[78, 12, 43],
       [98, 87, 47]])

In [ ]:
np.sort(a,axis=None)

array([12, 43, 47, 78, 87, 98])

In [ ]:
np.argsort(a,axis=0) 

array([[0, 1, 0],
       [1, 0, 1]])

In [ ]:
a[0,:]

array([78, 87, 43])

In [ ]:
np.argsort(a[0,:])

array([2, 0, 1])

In [ ]:
a[:,np.argsort(a[0,:])]   

array([[43, 78, 87],
       [47, 98, 12]])

### 10.3 數學矩陣的相關運算

#### 10.3.1 矩陣常用的運算

In [ ]:
a=np.array([0,1,2])

In [ ]:
b=np.array([3,4,5])

In [ ]:
vr=np.array([[3,4,5]])      

In [ ]:
m=np.array([[2,3,1,1], 
            [3,0,1,0],
            [1,0,3,2]])

In [ ]:
np.dot(a,b)   

14

In [ ]:
np.dot(2,m)

array([[4, 6, 2, 2],
       [6, 0, 2, 0],
       [2, 0, 6, 4]])

In [ ]:
np.dot(vr,m)     

array([[23,  9, 22, 13]])

In [ ]:
np.matmul(vr,m)    

array([[23,  9, 22, 13]])

In [ ]:
vr @ m             

array([[23,  9, 22, 13]])

In [ ]:
m @ m.T

array([[15,  7,  7],
       [ 7, 10,  6],
       [ 7,  6, 14]])

#### 10.3.2 使用 numpy.linalg 模組

In [ ]:
import numpy.linalg as la

In [ ]:
m=np.array([[1,4],[3,-1]])

In [ ]:
b=np.array([[6],[5]])

In [ ]:
la.inv(m)

array([[ 0.07692308,  0.30769231],
       [ 0.23076923, -0.07692308]])

In [ ]:
m @ la.inv(m)    

array([[1., 0.],
       [0., 1.]])

In [ ]:
la.inv(m) @ b      

array([[2.],
       [1.]])

In [ ]:
la.solve(m,b)     

array([[2.],
       [1.]])

In [ ]:
la.eig(m)

(array([ 3.60555128, -3.60555128]), array([[ 0.83791185, -0.65572799],
        [ 0.54580557,  0.75499722]]))

In [ ]:
la.eigvals(m)

array([ 3.60555128, -3.60555128])

In [ ]:
a=np.array([[ 1, 2],
            [ 3, 5],
            [-1, 1]])

In [ ]:
b=np.array([[4,8,5]]).T

In [ ]:
la.inv(a.T@a)@a.T@b    

array([[-2.13513514],
       [ 2.90540541]])

In [ ]:
la.lstsq(a,b,rcond=None)    

(array([[-2.13513514],
        [ 2.90540541]]),
 array([0.12162162]),
 2,
 array([6.25362248, 1.37557476]))

In [ ]:
np.sum((a@np.array([[-2.135],[2.905]])-b)**2)

0.12162499999999987

### 10.4 廣播運算

In [ ]:
a=np.arange(6).reshape(2,3)

In [ ]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
b=np.ones((2,3),dtype=int)

In [ ]:
b

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
a+b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a+1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a+np.array([[0,1,3]])

array([[0, 2, 5],
       [3, 5, 8]])

In [ ]:
a+np.array([0,1,3])  

array([[0, 2, 5],
       [3, 5, 8]])

In [ ]:
a+np.array([[1],
            [4]])

array([[1, 2, 3],
       [7, 8, 9]])

In [ ]:
c=np.array([[0],
            [1],
            [2]])

In [ ]:
d=np.array([[3,4,5,6]])

In [ ]:
c+d

array([[3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

In [ ]:
pa=np.array([[2,4,5],
             [3,3,4]])

In [ ]:
pb=np.array([[3,4,5,6],
             [0,7,2,1]])

In [ ]:
s_dist=np.zeros((3,4),dtype=int)   # 定義陣列s_dist
for i in range(3):
    for j in range(4):
        s_dist[i,j]=((pa[:,i]-pb[:,j])**2).sum()  # 計算距離的平方

In [ ]:
s_dist

array([[10, 20, 10, 20],
       [10, 16,  2,  8],
       [20, 10,  4, 10]])

In [ ]:
d=(pa[:,:,None]-pb[:,None,:])

In [ ]:
d

array([[[-1, -2, -3, -4],
        [ 1,  0, -1, -2],
        [ 2,  1,  0, -1]],

       [[ 3, -4,  1,  2],
        [ 3, -4,  1,  2],
        [ 4, -3,  2,  3]]])

In [ ]:
np.sum(d**2,axis=0)

array([[10, 20, 10, 20],
       [10, 16,  2,  8],
       [20, 10,  4, 10]])

In [ ]:
def dist_for(pa,pb):
    r,c=pa.shape[1],pb.shape[1]
    dist=np.zeros((r,c),dtype=int)
    for i in range(r):
        for j in range(c):
            dist[i,j]=((pa[:,i]-pb[:,j])**2).sum()
    return dist

In [ ]:
def dist_brocast(pa,pb):
    return np.sum((pa[:,:,None]-pb[:,None,:])**2,axis=0)

In [ ]:
%timeit dist_for(pa,pb)

10000 loops, best of 5: 71.4 µs per loop


In [ ]:
%timeit dist_brocast(pa,pb)

The slowest run took 11.26 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 9 µs per loop


In [ ]:
pa=np.random.randint(0,10,size=(2,400))
pb=np.random.randint(0,10,size=(2,1600))

In [ ]:
%timeit dist_for(pa,pb)

1 loop, best of 5: 2.69 s per loop


In [ ]:
%timeit dist_brocast(pa,pb)

100 loops, best of 5: 5.07 ms per loop


### 10.5 儲存 numpy 陣列

In [ ]:
import pickle

In [ ]:
arr=np.array([1,2,3])

In [ ]:
z=pickle.dumps(arr)

In [ ]:
pickle.loads(z)

array([1, 2, 3])

In [ ]:
len(z)

177

In [ ]:
z2=arr.tobytes()

In [ ]:
len(z2)

24

In [ ]:
np.frombuffer(z2,dtype=int)

array([1, 2, 3])

In [ ]:
z3=arr.astype(float).tobytes()

In [ ]:
np.frombuffer(z3)

array([1., 2., 3.])

In [ ]:
len(z3)

24

In [ ]:
np.save('test',arr)

In [ ]:
np.load('test.npy')

array([1, 2, 3])

In [ ]:
arr2=np.array(['Python'],dtype=object)

In [ ]:
np.save('test2',arr2)

In [ ]:
np.load('test2.npy',allow_pickle=True)

array(['Python'], dtype=object)

In [ ]:
age=np.array([21,20,20])

In [ ]:
height=np.array([172,183,176])

In [ ]:
np.savez('example',age_v=age,height_v=height)

In [ ]:
npz_file=np.load('example.npz')

In [ ]:
npz_file['age_v']

array([21, 20, 20])

In [ ]:
npz_file['height_v']

array([172, 183, 176])